# The path to the directory of the current playbook being executed (<PATH>/dotfiles-ansible)
roles_parent_dir: "{{ playbook_dir }}"

user_home_dir: "{{ '~' | ansible.builtin.expanduser }}"

config_home: "{{ user_home_dir }}/.config"

alias_home: "{{ config_home }}/aliases"

completions:
  zsh: "{{ config_home }}/completions/zsh"
  bash: "{{ config_home }}/completions/bash"
