#  Local home directory
dotfiles_user_home: "{{ '~' | expanduser }}"
# Where your dotfiles live. Probably don't need to change this.
dotfiles_home: "{{ dotfiles_user_home }}/projects/dotfiles-ansible"

# Name used in commit messages
full_name: sildvauresberg
# Github username
git_user: sildvauresberg
# If you use github, this should be the same as the email used on Github
git_email: slickunit4265752@gmail.com

# Utilities that do not get installed by a role
mac_homebrew_packages:
  - coreutils
  - starship
#  - protobuf
#  - websocat
#  - glances
#  - youtube-dl
  - bat
  - exa
  - fzf
#  - jq
#  - yq
#  - mkcert # https://github.com/FiloSottile/mkcert see PiterJS #50 on youtube

# Mac Apps to be installed with homebrew-cask
mac_cask_packages:
  - rectangle
  - docker
  - telegram
  - intellij-idea
  - vlc
#  - windscribe
