import = []

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Underline"
vi_mode_style = "Block"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.95
option_as_alt = "OnlyLeft"

[window.padding]
x = 3
y = 3
