[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 3
# truncate_symbol = '.../'

[kubernetes]
disabled = false
