[[ $- != *i* ]] && return

test -e ~/.dircolors && command -v gdircolors &> /dev/null && eval `gdircolors -b ~/.dircolors`

fpath=(~/.zsh_custom/completion $fpath)

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' list-colors $LS_COLORS

autoload -Uz compinit
zmodload zsh/complist
compinit -i
_comp_options+=(globdots)

for f in ~/.zsh_custom/*; do source "$f"; done

source ~/projects/dotfiles-ansible/roles/zsh/zsh_plugins/z/z.sh
source ~/projects/dotfiles-ansible/roles/zsh/zsh_plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source ~/projects/dotfiles-ansible/roles/zsh/zsh_plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

FZF_DEFAULT_OPTS="
  --bind 'ctrl-f:page-down,ctrl-b:page-up,ctrl-o:execute(code {})+abort'
  --color fg:102,bg:233,hl:65,fg+:15,bg+:234,hl+:108
  --color info:108,prompt:109,spinner:108,pointer:168,marker:168
"
test -f ~/.fzf.zsh && source ~/.fzf.zsh

export STARSHIP_CONFIG=~/.starship.toml
eval "$(starship init zsh)"
