# - name: Sync .bashrc
#   ansible.builtin.template:
#     src: "bashrc.j2"
#     dest: "{{ user_home_dir }}/.bashrc"
#   when: ansible_facts['user_shell'].endswith('bash')

- name: Adapt bashrc file
  ansible.builtin.lineinfile:
    backup: true
    path: "{{ user_home_dir }}/.bashrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - {regexp: '^for i in $(find ~/.config/aliases -mindepth 1 -maxdepth 1 -type f); do source "$i"; done', line: 'for i in $(find ~/.config/aliases -mindepth 1 -maxdepth 1 -type f); do source "$i"; done'}
    - {regexp: '^unset PROMPT_COMMAND', line: 'unset PROMPT_COMMAND'}
    - {regexp: '^export FZF_DEFAULT_OPTS', line: 'export FZF_DEFAULT_OPTS="--color=fg+:#ff8dc8,hl+:#ff8dc8 --preview-window=\"border-sharp\""'}
    - {regexp: '^eval "$(fzf --bash)"', line: 'eval "$(fzf --bash)"'}
    - {regexp: '^eval "$(zoxide init bash)"', line: 'eval "$(zoxide init bash)"'}
    - {regexp: '^eval "$(starship init bash)"', line: 'eval "$(starship init bash)"'}
  when: ansible_facts['user_shell'].endswith('bash')
