- name: Set up local development environment
  hosts: local
  become: no
  # TODO: Move this to ZSH role
  pre_tasks:
    - name: Create directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ zsh_home }}"
        - "{{ zsh.plugin_home }}"
        - "{{ zsh.alias_home }}"
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - {role: docker, tags: ["docker"]}
    - {role: git, tags: ["git"]}
    - {role: k8s, tags: ["k8s"]}
    - {role: macos, tags: ["macos"], when: ansible_os_family == "Darwin"}
    - {role: packer, tags: ["packer"]}
    - {role: terraform, tags: ["terraform"]}
    - {role: tmux, tags: ["tmux"]}
    - {role: vim, tags: ["vim"]}
    - {role: zsh, tags: ["zsh"]}
