- name: Set up a local development environment
  hosts: local
  become: false
  pre_tasks:
    - block:
        - name: Retrieve HOMEBREW_PREFIX
          ansible.builtin.command: brew --prefix
          register: brew_prefix_data
          changed_when: false
        - name: Register HOMEBREW_PREFIX
          ansible.builtin.set_fact:
            brew_prefix: "{{ brew_prefix_data.stdout }}"
        - name: Ensure essential directories exist
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0755"
          loop:
            - "{{ config_home }}"
            - "{{ alias_home }}"
            - "{{ completions.zsh }}"
      tags:
        - always
  roles:
    # Tag each role so that one can select individual roles to run with ansible-playbook --tags
    - {role: bash, tags: ["bash"]}
    - {role: docker, tags: ["docker"]}
    - {role: frontend, tags: ["frontend"]}
    - {role: git, tags: ["git"]}
    - {role: go, tags: ["go"]}
    - {role: jvm, tags: ["jvm"]}
    - {role: k8s, tags: ["k8s"]}
    - {role: media, tags: ["media"]}
    - {role: remote_dev_machine, tags: ["remote_dev_machine"]}
    - {role: toolbox, tags: ["toolbox"]}
    - {role: web_server, tags: ["web_server"]}
    - {role: zig, tags: ["zig"]}
    - {role: zsh, tags: ["zsh"]}
