- name: Set up a local development environment
  hosts: local
  become: false
  pre_tasks:
    - block:
        - name: Retrieve HOMEBREW_PREFIX
          ansible.builtin.command: brew --prefix
          register: brew_prefix_data
          changed_when: false
        - name: Register HOMEBREW_PREFIX
          ansible.builtin.set_fact:
            brew_prefix: "{{ brew_prefix_data.stdout }}"
        - name: Ensure essential directories exist
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0755"
          loop:
            - "{{ config_home }}"
            - "{{ alias_home }}"
      tags:
        - always
  roles:
    - {role: bash, tags: ["bash"]}
    - {role: common, tags: ["common"]}
    - {role: dev, tags: ["dev"]}
    - {role: docker, tags: ["docker"]}
    - {role: go, tags: ["go"]}
    - {role: home, tags: ["home"]}
    - {role: jvm, tags: ["jvm"]}
    - {role: k8s, tags: ["k8s"]}
    - {role: zig, tags: ["zig"]}
    - {role: zsh, tags: ["zsh"]}
