- name: Set up a local development environment
  hosts: local
  become: false
  roles:
    # Tag each role so that one can select individual roles to run with ansible-playbook --tags
    - {role: docker, tags: ["docker"]}
    - {role: frontend, tags: ["frontend"]}
    - {role: git, tags: ["git"]}
    - {role: jvm, tags: ["jvm"]}
    - {role: k8s, tags: ["k8s"]}
    - {role: media, tags: ["media"]}
    - {role: remote_dev_machine, tags: ["remote_dev_machine"]}
    - {role: toolbox, tags: ["toolbox"]}
    - {role: web_server, tags: ["web_server"]}
    - {role: zig, tags: ["zig"]}
    - {role: zsh, tags: ["zsh"]}
