"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$container\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$cmd_duration\
$line_break\
$jobs\
$character"""

[git_branch]
symbol = ''

[container]
format = '[$symbol]($style) '

[cmd_duration]
disabled = true

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
