- name: Install build-essential
  ansible.builtin.apt:
    autoclean: yes # Remove undownloadable packages from the cache
    autoremove: yes # Remove dependencies that are no longer required
    update_cache: yes
    upgrade: dist
    name: build-essential
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Configure OpenSSH Daemon
  ansible.builtin.lineinfile:
    backup: true
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^AllowTcpForwarding', line: 'AllowTcpForwarding yes' }
    - { regexp: '^AllowAgentForwarding', line: 'AllowAgentForwarding yes' }
  when: ansible_system == "Linux"
