# exit if not running interactively
[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000
# check the window size after each command and,
# if necessary, update the values of LINES and COLUMNS.
shopt -s checkwinsize
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
[ -f ~/.bash_aliases ] && source ~/.bash_aliases
# enable programmable comp features if in not POSIX mode
! shopt -oq posix && {
  [ -f /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion ||
  [ -f /etc/bash_completion ] && . /etc/bash_completion
}
# export PATH="$HOME/.local/bin:$PATH"

# ---

# for i in $(find ~/.config/aliases -mindepth 1 -maxdepth 1 -type f); do source "$i"; done

# for cmp in /home/linuxbrew/.linuxbrew/etc/bash_completion.d/*; do source "$cmp"; done

[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export FZF_DEFAULT_OPTS='--color=fg+:#ff8dc8,hl+:#ff8dc8 --preview-window="border-sharp"'
command -v fzf && eval "$(fzf --bash)"
command -v starship && eval "$(starship init bash)"
command -v zoxide && eval "$(zoxide init bash)"

# Workaround for VSCode Remote SSH Extension + tmux
# unset PROMPT_COMMAND
