- name: Set MacOS defaults
  ansible.builtin.script: set-defaults.sh
  become: yes
  when: defaults

- name: Check if Terminal.app theme is Snazzy
  community.general.osx_defaults:
    domain: com.apple.Terminal
    key: "{{ item }}"
    state: list
  loop:
    - Default Window Settings
    - Startup Window Settings
  register: profiles
- name: Install Terminal.app theme
  when: profiles.results | selectattr('value', '==', 'Snazzy') | list | length == 0
  block:
    - name: Allow unverified app
      ansible.builtin.command: xattr -dr com.apple.quarantine {{ roles_parent_dir}}/roles/macos/files/Snazzy.terminal
      register: xattr_result
    - name: Open theme via Terminal.app
      ansible.builtin.command: open {{ roles_parent_dir }}/roles/macos/files/Snazzy.terminal
    - name: Override Default & Startup theme
      community.general.osx_defaults:
        domain: com.apple.Terminal
        key: "{{ item }}"
        value: "Snazzy"
      loop:
        - Default Window Settings
        - Startup Window Settings
  rescue:
    - name: Print when errors
      ansible.builtin.debug:
        var: xattr_result

- name: Install packages with homebrew formula
  community.general.homebrew:
    name: "{{ mac.homebrew.formula }}"
    state: present

- name: Install applications with homebrew cask
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ mac.homebrew.cask | flatten(levels=1) }}"
