- name: Set system deafults
  script: set-defaults.sh
  register: script_result
  failed_when: script_result.rc != 1

- name: Install mac-specific homebrew packages
  homebrew:
    name: "{{ mac_homebrew_packages }}"
    state: present

- name: Install Mac apps with homebrew cask
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ mac_cask_packages | flatten(levels=1) }}"

- name: Install Terminal.app theme
  command: open {{ dotfiles_home }}/roles/macos/files/Snazzy.terminalcolors
  when: false
