- block:
    - name: Setup ZSH on Linux
      ansible.builtin.include_tasks: setup-zsh.yml
      when:
        - ansible_system == "Linux"

    - name: Create directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ zsh_home }}"
        - "{{ zsh.plugin_home }}"
        - "{{ completions.zsh }}"

    - name: Copy history config file
      ansible.builtin.copy:
        src: "history.sh"
        dest: "{{ zsh_home }}/history.sh"

    - name: Sync .zshrc
      ansible.builtin.template:
        src: "zshrc.j2"
        dest: "{{ user_home_dir }}/.zshrc"

    # TODO: Add auto update support
    - name: Clone plugins
      ansible.builtin.git:
        repo: "https://github.com/{{ item.uri }}"
        dest: "{{ zsh.plugin_home }}/{{ item.name }}"
        single_branch: true
        version: master
      loop:
        - {uri: "zsh-users/zsh-autosuggestions.git", name: "zsh-autosuggestions"}
        # - {uri: "zsh-users/zsh-syntax-highlighting.git", name: "zsh-syntax-highlighting"}
        - {uri: "zdharma-continuum/fast-syntax-highlighting.git", name: "fast-syntax-highlighting"}
  when: ansible_facts['user_shell'].endswith('zsh')
