#- name: Install fzf completion & key-bindings
#  shell: $(brew --prefix)/opt/fzf/install --no-bash --no-update-rc --key-bindings --completion

- name: Copy LS_COLORS
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/dircolors"
    dest: "{{ '~/.dircolors' | expanduser }}"

- name: Copy starship prompt config
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/starship.toml"
    dest: "{{ '~/.starship.toml' | expanduser }}"

- name: Copy zsh_custom plugin
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/zsh_custom/"
    dest: "{{ zsh_custom_plugin_home }}"

- name: Copy zshrc
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc"
    dest: "{{ '~/.zshrc' | expanduser }}"

- name: Create a directory if it does not exist
  file:
    path: "{{ zsh_completion_home }}"
    state: directory
    mode: "0755"

- name: Download docker completion
  get_url:
    url: https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker
    dest: "{{ zsh_completion_home }}/_docker"
    mode: "0440"

# TODO: uncomment if docker compose has no completion
#- name: Download docker-compose completion
#  get_url:
#    url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose
#    dest: "{{ zsh_completion_home }}/_docker-compose"
#    mode: "0440"
