- name: Check if a `.fzf.zsh` file exists
  stat:
    path: "{{ dotfiles_user_home }}/.fzf.zsh"
  register: file_data

- name: Generate fzf completion & key-bindings
  shell: $(brew --prefix)/opt/fzf/install --no-bash --no-update-rc --key-bindings --completion
  when: not file_data.stat.exists

- name: Copy prompt config
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/starship.toml"
    dest: "{{ '~/.starship.toml' | expanduser }}"

- name: Copy common aliases, functions, etc.
  copy:
    src: "{{ item }}"
    dest: "{{ zsh_custom_plugin_home }}"
  with_fileglob:
    - "{{ dotfiles_home }}/roles/zsh/files/zsh_custom/*"

- name: Create .zshrc
  template:
    src: "zshrc.j2"
    dest: "{{ '~/.zshrc' | expanduser }}"

- name: Clone plugins
  ansible.builtin.git:
    repo: "https://github.com/{{ item.uri }}"
    dest: "{{ zsh_plugin_home }}/{{ item.name }}"
    single_branch: yes
    version: master
  loop:
    - { uri: "zsh-users/zsh-autosuggestions.git", name: "zsh-autosuggestions"}
    - { uri: "zsh-users/zsh-syntax-highlighting.git", name: "zsh-syntax-highlighting"}
    - { uri: "rupa/z.git", name: "z"}

- name: Install prompt
  ansible.builtin.package:
    name: starship
    state: present

- name: Download fonts
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/{{ item }}"
    dest: ~/Library/Fonts
    mode: "644"
  loop:
    - JetBrainsMono/NoLigatures/Bold/complete/JetBrains%20Mono%20NL%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
    - JetBrainsMono/NoLigatures/Italic/complete/JetBrains%20Mono%20NL%20Italic%20Nerd%20Font%20Complete%20Mono.ttf
    - JetBrainsMono/NoLigatures/Regular/complete/JetBrains%20Mono%20NL%20Regular%20Nerd%20Font%20Complete%20Mono.ttf

