#- name: Install fzf completion & key-bindings
#  shell: $(brew --prefix)/opt/fzf/install --no-bash --no-update-rc --key-bindings --completion

- name: Symlink LS_COLORS
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/dircolors.link"
    dest: "{{ '~/.dircolors' | expanduser }}"
    state: link

- name: Symlink starship prompt config
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/starship.link"
    dest: "{{ '~/.starship.toml' | expanduser }}"
    state: link

- name: Symlink zsh_custom plugin
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zsh_custom"
    dest: "{{ '~/.zsh_custom' | expanduser }}"
    state: link

- name: Symlink zshrc
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc.link"
    dest: "{{ '~/.zshrc' | expanduser }}"
    state: link
