- name: Symlink LS_COLORS
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/dircolors.link"
    dest: "{{ '~/.dircolors' | expanduser }}"
    state: link

- name: Symlink p10k theme
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/p10k.link"
    dest: "{{ '~/.p10k.zsh' | expanduser }}"
    state: link

- name: Symlink zsh_custom plugin
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zsh_custom"
    dest: "{{ '~/.zsh_custom' | expanduser }}"
    state: link

- name: Symlink zshrc
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc.link"
    dest: "{{ '~/.zshrc' | expanduser }}"
    state: link