# TODO: figure out what is going on
#- name: Install fzf completion & key-bindings
#  shell: $(brew --prefix)/opt/fzf/install --no-bash --no-update-rc --key-bindings --completion

- name: Copy LS_COLORS
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/dircolors"
    dest: "{{ '~/.dircolors' | expanduser }}"

- name: Copy starship prompt config
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/starship.toml"
    dest: "{{ '~/.starship.toml' | expanduser }}"

- name: Copy zsh_custom plugin
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/zsh_custom/"
    dest: "{{ zsh_custom_plugin_home }}"

- name: Copy zshrc
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc"
    dest: "{{ '~/.zshrc' | expanduser }}"

- name: Create a directory if it does not exist
  file:
    path: "{{ zsh_completion_home }}"
    state: directory
    mode: "0755"
