- name: Check if zsh is already installed
  ansible.builtin.shell: command -v zsh
  register: zsh_cmd_data
  changed_when: false

- name: Install zsh
  community.general.homebrew:
    name: zsh
  when: zsh_cmd_data.rc != 0

- name: Make zsh default shell for the current user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /home/linuxbrew/.linuxbrew/bin/zsh   # TODO: use output from zsh_cmd_data
  become: true
  tags: never   # TODO: test
