- name: Install JDKs & SDKs
  ansible.builtin.import_role:
    name: comcast.sdkman
  vars:
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_install_packages:
      - {candidate: java, version: '22-graalce'}
      - {candidate: gradle, version: '8.7'}
      - {candidate: maven, version: '3.9.6'}
