- name: Ensure roles path exists
  ansible.builtin.file:
    path: "{{ user_home_dir }}/.ansible/roles"
    state: directory
    mode: '0755'

- name: Check whether sdkman ansible role is installed or not
  ansible.builtin.command: ansible-galaxy list comcast.sdkman
  register: role_data
  changed_when: false

- name: Install sdkman ansible role
  ansible.builtin.command: ansible-galaxy role install comcast.sdkman
  when: '"comcast.sdkman" not in role_data.stdout'

- name: Install JDKs & SDKs
  ansible.builtin.include_role:
    name: comcast.sdkman
  vars:
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_install_packages:
      - {candidate: java, version: '22-graalce'}
      - {candidate: gradle, version: '8.7'}
      - {candidate: maven, version: '3.9.6'}
