- name: Ensure alacritty directory exists
  ansible.builtin.file:
    path: "{{ alacritty_config_dir }}"
    state: directory
    mode: "0755"

# - name: Clone themes repository
#   ansible.builtin.git:
#     repo: "https://github.com/alacritty/alacritty-theme"
#     dest: "{{ alacritty_config_dir }}/themes"
#     single_branch: true
#     version: master

- name: Make sure Alacritty is configured
  ansible.builtin.copy:
    src: "alacritty.toml"
    dest: "{{ alacritty_config_dir }}/alacritty.toml"
