- name: Setup MacOS
  ansible.builtin.import_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- name: Add custom fonts
  ansible.builtin.import_tasks: fonts.yml
  when: ansible_os_family == "Darwin" or ansible_distribution == "Ubuntu"

- name: Install homebrew casks
  ansible.builtin.import_tasks: homebrew-casks.yml

- name: Configure Alacritty terminal
  ansible.builtin.import_tasks: alacritty.yml

- name: Configure VSCode
  ansible.builtin.import_tasks: vscode.yml
