- name: check if VSCode is installed
  ansible.builtin.command: 'code --version'
  register: vscode_version_data
  changed_when: false

- name: install essential extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  loop:
    - 'drcika.apc-extension'
    - 'editorconfig.editorconfig'
    # - 'github.github-vscode-theme'
    # - 'marlosirapuan.nord-deep'
    # - 'ms-vscode-remote.remote-containers'
    # - 'ms-vscode-remote.remote-ssh'
    # - 'ms-vscode-remote.remote-ssh-edit'
    # - 'ms-vscode.remote-explorer'
    - 'timonwong.shellcheck'
  when: vscode_version_data.rc != 0

- name: copy VSCode config
  ansible.builtin.copy:
    src: "vscode.json"
    dest: "{{ user_home_dir }}/Library/Application\ Support/Code/User/settings.json"
