"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 3
# truncate_symbol = '.../'

[gradle]
disabled = true
[java]
disabled = true
[kotlin]
disabled = true
[golang]
disabled = true
