- name: Remove certbot-auto and any Certbot OS packages
  ansible.builtin.apt:
    name: certbot
    state: absent

- name: Install certbot
  community.general.snap:
    name: certbot
    state: present
    classic: true

- name: Prepare the Certbot command
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
