- name: Copy editorconfig
  ansible.builtin.copy:
    src: "{{ roles_parent_dir }}/.editorconfig"
    dest: "{{ user_home_dir }}/.editorconfig"

- name: Copy global gitignore
  ansible.builtin.copy:
    src: "{{ roles_parent_dir }}/.gitignore"
    dest: "{{ user_home_dir }}/.gitignore"

- name: Make sure gitconfig is up to date
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: "{{ user_home_dir }}/.gitconfig"

- name: Copy git aliases into alias home
  ansible.builtin.copy:
    src: "git.sh"
    dest: "{{ alias_home }}/git.sh"
