- name: Install Helix Editor on Linux
  block:
    - name: Add the PPA for Helix
      ansible.builtin.apt_repository:
        repo: ppa:maveonair/helix-editor
    - ansible.builtin.apt:
        name: helix
  when: ansible_distribution == "Ubuntu"

- name: Install Helix Editor on MacOS
  community.general.homebrew:
    name: helix
  when: ansible_os_family == "Darwin"

- name: Make sure Helix Editor is configured
  ansible.builtin.copy:
    src: "config.toml"
    dest: "{{ helix_config_dir }}/config.toml"