- name: Install tmux on Linux
  ansible.builtin.apt:
    name: tmux
  when: ansible_distribution == "Ubuntu"

- name: Install tmux on MacOS
  community.general.homebrew:
    name: tmux
  when: ansible_os_family == "Darwin"

- name: Ensure tmux dir exists
  ansible.builtin.file:
    path: "{{ config_home }}/tmux"
    state: directory

- name: Copy tmux config 
  ansible.builtin.copy:
    src: "tmux.conf"
    dest: "{{ config_home }}/tmux/tmux.conf"
