syntax on
set number
set hlsearch
set encoding=utf-8
set tabstop=2
set softtabstop=2
set shiftwidth=2
set textwidth=80
set smarttab
set expandtab
set autoindent
set smartindent
set fileformat=unix
set relativenumber

autocmd FileType make setlocal noexpandtab
