" Sets how many lines of history VIM has to remember
set history=10

set scrolloff=999

" Disable swap file
set noswapfile

" Set to auto read when a file is changed from the outside
set autoread
au FocusGained,BufEnter * checktime

syntax on

" Turn on the Wild menu
set wildmenu

set number
set hlsearch
set encoding=utf-8
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab
set expandtab
set wrap
set showmatch
set incsearch
set autoindent
set smartindent
set fileformat=unix
set fencs=utf-8
set relativenumber

autocmd FileType make setlocal noexpandtab
