- name: Install OpenJDK
  ansible.builtin.package:
    name: openjdk
    state: present

# TODO: symlink via file module
- name: Symlink OpenJDK
#  become: true
  shell: ln -sfn "$(brew --prefix)"/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

- name: Install Maven build tool
  ansible.builtin.package:
    name: maven
    state: present

- name: Install Gradle build tool
  ansible.builtin.package:
    name: gradle
    state: present

- name: Copy java aliases into zsh_custom directory
  copy:
    src: "{{ dotfiles_home }}/roles/java/files/java.sh"
    dest: "{{ zsh_custom_plugin_home }}/java.sh"
