# https://alpha2phi.medium.com/a-walkthrough-on-helix-a-post-modern-modal-text-editor-faf573d16892

# theme = "catppuccin_mocha"
theme = "base16_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = false
true-color = true
color-modes = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
center = ["diagnostics"]
right = ["position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
