# https://alpha2phi.medium.com/a-walkthrough-on-helix-a-post-modern-modal-text-editor-faf573d16892

theme = "nord"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
mouse = false
true-color = true
color-modes = true
scrolloff = 10

[editor.file-picker]
hidden = false
parents = false
git-ignore = false

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
center = ["diagnostics"]
right = ["position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-l = ["normal_mode", "save_selection", "extend_to_line_bounds", "yank_to_primary_clipboard", "paste_primary_clipboard_before", "jump_backward", "insert_mode"]
