"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[git_branch]
symbol = ''
[git_status]
disabled = true
[golang]
disabled = true
[gradle]
disabled = true
[java]
disabled = true
[kotlin]
disabled = true
[nodejs]
disabled = true
[perl]
disabled = true
[ruby]
disabled = true

