"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[directory]
truncate_to_repo = false
truncation_symbol = '.../'
# fish_style_pwd_dir_length = 3

[golang]
disabled = true
[gradle]
disabled = true
[java]
disabled = true
[kotlin]
disabled = true
[nodejs]
disabled = true
[perl]
disabled = true
[ruby]
disabled = true

