" colorscheme murphy

syntax on

set ttyfast
set laststatus=1            "-- Show status line iff 2+ windows
set showcmd                 "-- Show last command
set cursorline              "-- Highlight current line

set termguicolors           "-- Enable 24-bit RGB colors
set autowrite               "-- Automatically save before :next, :make etc.
set autochdir               "-- Change CWD when one have opened a file
set splitbelow              "-- Split windows below to the current window
set splitright              "-- Split windows right to the current window
set clipboard=unnamedplus   "-- Copy & paste to the system clipboard
set ignorecase              "-- search case insensitive...
set smartcase               "-- ... but not if begins with upper case

set autoindent              "-- Copy indent from current line when starting a new line
set encoding=utf-8
set expandtab               "-- Expand tabs into spaces
set fencs=utf-8
set fileformat=unix
set history=10
set hlsearch
set incsearch
set noswapfile              "-- Do not use swapfile
set number                  "-- Show line numbers
set relativenumber
set scrolloff=999
set shiftwidth=2            "-- Number of spaces to use for each step of indent
set showmatch               "-- Highlight matching parenthesis
set smartindent
set smarttab
set softtabstop=2
set tabstop=2               "-- Number of spaces a TAB counts for
set viminfofile=NONE        "-- Completely disable .viminfo logging
set wildmenu
set wrap

autocmd FileType make setlocal noexpandtab
