[colors]
draw_bold_text_with_bright_colors = false
cursor = {text = '#F38BA3', cursor = '#F38BA3'}
selection = {text = "#0F0D0E", background = "#44C9F0"}
[colors.primary]
background = '#0F0D0E'
foreground  = '#F9F4DA'
dim_foreground = '#ECDC8A'
bright_foreground = '#F2EFE2'
[colors.normal]
black = '#4C4345'
blue = '#006EE6'
cyan = '#88DAF2'
green = '#0BA95B'
magenta = '#7B5EA7'
red = '#ED203D'
white = '#F1F1F1'
yellow = '#FCBA28'
[colors.bright]
black = '#ADA8A0'
blue = '#44C9F0'
cyan = '#7BE1FF'
green = '#0ED372'
magenta = '#9E88BE'
red = '#F25E73'
white = '#FFFFFF'
yellow = '#FDF170'
[colors.dim]
black = '#1C191A'
blue = '#0E91B7'
cyan = '#93D4E7'
green = '#098749'
magenta = '#624A87'
red = '#C7102A'
white = '#C1C1C1'
yellow = '#E6A003'

[cursor]
style = "Beam"
vi_mode_style = "Block"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.95
option_as_alt = "OnlyLeft"

[window.padding]
x = 3
y = 3
