- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present

- name: Copy tmux config 
  copy:
    src: "{{ roles_parent_dir }}/roles/tmux/files/tmux.conf"
    dest: "{{ user_home_dir }}/.tmux.conf"
