- name: Install brew packages
  community.general.homebrew:
    name:
      - bat
      - eza
      - fastfetch
      - fzf
      - helix
      - starship
      - tmux
      - zoxide
    update_homebrew: true
    upgrade_all: true

- name: Copy bat config
  block:
    - ansible.builtin.file:
        path: "{{ config_home }}/bat"
        state: directory
    - ansible.builtin.copy:
        src: "bat.cfg"
        dest: "{{ config_home }}/bat/config"

- name: Configure Helix Editor
  block:
    - name: Ensure helix config dir exists
      ansible.builtin.file:
        path: "{{ config_home }}/helix"
        state: directory
    - name: Copy helix config
      ansible.builtin.copy:
        src: "helix.toml"
        dest: "{{ config_home }}/helix/config.toml"

- name: Copy starship config
  ansible.builtin.copy:
    src: "starship.toml"
    dest: "{{ config_home }}/starship.toml"

- name: Configure tmux
  block:
    - name: Ensure tmux dir exists
      ansible.builtin.file:
        path: "{{ config_home }}/tmux"
        state: directory
    - name: Copy tmux config
      ansible.builtin.copy:
        src: "tmux.conf"
        dest: "{{ config_home }}/tmux/tmux.conf"

- name: Copy vim config
  ansible.builtin.copy:
    src: "vimrc"
    dest: "{{ user_home_dir }}/.vimrc"

- name: Copy aliases, functions, etc.
  ansible.builtin.copy:
    src: "utilities.sh"
    dest: "{{ alias_home }}/utilities.sh"

- name: Copy editorconfig
  ansible.builtin.copy:
    src: "{{ roles_parent_dir }}/.editorconfig"
    dest: "{{ user_home_dir }}/.editorconfig"

- name: Make sure gitconfig is up to date
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: "{{ user_home_dir }}/.gitconfig"

- name: Copy git aliases into alias home
  ansible.builtin.copy:
    src: "git.sh"
    dest: "{{ alias_home }}/git.sh"
