- name: Make sure snap is installed
  ansible.builtin.apt:
    name: snapd

- name: Start service snapd, if not started
  ansible.builtin.service:
    name: snapd
    state: started

- name: Make sure a snapd service unit is running
  ansible.builtin.systemd:
    name: snapd
    state: started
