- name: '[buildx] Ensure a CLI plugins directory exists'
  ansible.builtin.file:
    path: "{{ user_home_dir }}/.docker/cli-plugins"
    state: directory

- name: '[buildx] Create a symbolic link'
  ansible.builtin.file:
    src: "{{ brew_prefix }}/opt/docker-buildx/bin/docker-buildx"
    dest: "{{ user_home_dir }}/.docker/cli-plugins/docker-buildx"
    state: link
    force: true
