# TODO: should be optional
- name: Install colima
  community.general.homebrew:
    name: colima
    state: present

# TODO: should be optional
- name: Install docker & docker-compose
  community.general.homebrew:
    name:
      - docker
      - docker-compose
    state: present

- name: Enable docker CLI compose plugin
  ansible.builtin.import_tasks: compose.yaml
