- name: Install docker
  community.general.homebrew_cask:
    name: docker
    state: present

- name: Copy docker aliases into zsh alias directory
  copy:
    src: "{{ roles_parent_dir }}/roles/docker/files/docker.sh"
    dest: "{{ zsh.alias_home }}/docker.sh"
