# TODO: Should be optional
- name: Install colima
  community.general.homebrew:
    name: colima
    state: present

- name: Install docker related things
  community.general.homebrew:
    name:
      - docker
      - docker-compose
      - dive
    state: present

- name: Enable docker CLI compose plugin
  ansible.builtin.import_tasks: compose.yml
